DAIS_ASP/Controllers/OfficerController.cs
using DAIS_ORM.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAIS_ASP.Controllers
{
    public class OfficerController : Controller
    {
        //
        // GET: /Officer/
        public ActionResult Index()
        {
            ViewBag.Officers = OfficerTable.Select();
            ViewBag.Title = "Officers";

            return View();
        }

        public ActionResult Detail(Int32 Number)
        {
            Officer officer = OfficerTable.Select(Number);
            
            ViewBag.Officer = officer;
            ViewBag.Violations = ViolationTable.SelectOff(officer.Number);
            ViewBag.Title = "Officer detail";

            return View();
        }
	}
}

DAIS_ASP/Controllers/ViolationController.cs
using DAIS_ORM.Database;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAIS_ASP.Controllers
{
    public class ViolationController : Controller
    {
        //
        // GET: /Violation/
        public ActionResult Index()
        {
            ViewBag.Violations = ViolationTable.Select();
            ViewBag.Title = "Violations";

            return View();
        }

        public ActionResult Detail(Int32 Id)
        {
            Violation violation = ViolationTable.Select(Id);

            if (violation == null)
            {
                throw new HttpException(404, "Not Found");
            }

            ViewBag.Tickets = TicketTable.SelectV(Id);
            ViewBag.Violation = violation;
            ViewBag.Title = "Violation detail";

            return View();
        }

        [HttpGet]
        public ActionResult Violator()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Violator(String violator_birth_number)
        {
            Violator violator = ViolatorTable.Select(violator_birth_number);

            ViewBag.Violator = violator;
            ViewBag.Violations = ViolationTable.SelectVio(violator.Id);

            return View("Violator");
        }

        public ActionResult Pay(Int32 Id)
        {
            try
            {
                Ticket t = TicketTable.Select(Id);
                Procedures.PayTicket(t.Id, "cash");
            }
            catch (Exception)
            {
                throw new HttpException(500, "Error");
            }

            return Redirect("/Violation/Detail/" + Id);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Title = "New Violation";

            return View();
        }

        [HttpPost]
        public ActionResult Create(Int16? b)
        {
            try
            {
                Int32 number = Int32.Parse(Request.Form["officer_number"]);
                String birth_number = Request.Form["violator_birth_number"];
                String first_name = Request.Form["violator_first_name"];
                String last_name = Request.Form["violator_last_name"];
                String phone = Request.Form["violator_phone"];
                String state = Request.Form["violator_state"];
                String street = Request.Form["violator_street"];
                String city = Request.Form["violator_city"];
                String zip = Request.Form["violator_zip"];
                String licence = Request.Form["vehicle_licence"];
                String manufacturer = Request.Form["vehicle_manufacturer"];
                String model = Request.Form["vehicle_model"];
                Int32 year = Int32.Parse(Request.Form["vehicle_year"]);
                String type = Request.Form["violation_type"];
                Int32 amount = Int32.Parse(Request.Form["violation_amount"]);
                DateTime date = DateTime.Parse(Request.Form["violation_date"]);

                Procedures.NewTicket(number, birth_number, first_name, last_name, phone, state, street, city, zip, licence, manufacturer, model, year, type, amount, date);

                return View("CreateSuccess");
            }
            catch (Exception e)
            {
                return View("CreateFailure");
            }
        }
	}
}

DAIS_ASP/Views/Violation/Create.cshtml
@using DAIS_ORM.Database;

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                @Html.Partial("SubMenuViolation")
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <h1 class="page-header">New violation</h1>
            <div class="container-fluid">
                @using (Html.BeginForm("Create", "Violation", null, FormMethod.Post, new { @class = "form-horizontal"}))
                {
                    <div class="col-xs-12 form-group">
                        <legend>Officer</legend>
                        <div class="form-group">
                            @Html.Label("Officer Number", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-3">
                                @Html.TextBox("officer_number", "", new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 form-group">
                        <legend>Violator</legend>
                        <div class="form-group">
                            @Html.Label("Birth Number", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-5">
                                @Html.TextBox("violator_birth_number", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("First Name", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-5">
                                @Html.TextBox("violator_first_name", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Last Name", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-5">
                                @Html.TextBox("violator_last_name", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Phone", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-5">
                                @Html.TextBox("violator_phone", "", new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 form-group">
                        <legend>Address</legend>
                        <div class="form-group">
                            @Html.Label("State", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-5">
                                @Html.TextBox("violator_state", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Street", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-5">
                                @Html.TextBox("violator_street", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("City", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-5">
                                @Html.TextBox("violator_city", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Zip", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-3">
                                @Html.TextBox("violator_zip", "", new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 form-group">
                        <legend>Vehicle</legend>
                        <div class="form-group">
                            @Html.Label("Licence Number", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-2">
                                @Html.TextBox("vehicle_licence", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Manufacturer", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-3">
                                @Html.TextBox("vehicle_manufacturer", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Model", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-3">
                                @Html.TextBox("vehicle_model", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Year of manufacture", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-2">
                                @Html.TextBox("vehicle_year", "", new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 form-group">
                        <legend>Violation</legend>
                        <div class="form-group">
                            @Html.Label("Type", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-3">
                                @Html.TextArea("violation_type", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Amount", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-2">
                                @Html.TextBox("violation_amount", "", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Date", new { @class = "control-label col-xs-2" })
                            <div class="col-xs-2">
                                @Html.TextBox("violation_date", "", new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <input type="submit" value="Create" class="btn btn-primary"/>
                    </div>
                }
            </div>

        </div>
    </div>
</div>

DAIS_ASP/Views/Violation/CreateFailure.cshtml
@{
    ViewBag.Title = "CreateFailure";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                @Html.Partial("SubMenuViolation")
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <div class="container-fluid">
                <h2>New Violation</h2>
                <div class="alert alert-danger">
                    <p><strong>Create Failure</strong></p>
                    <p>There was an error creating new violation</p>
                </div>
                @Html.ActionLink("Go back", "Create", "Violation")
            </div>

        </div>
    </div>
</div>

DAIS_ASP/Views/Violation/CreateSuccess.cshtml
@{
    ViewBag.Title = "CreateSuccess";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                @Html.Partial("SubMenuViolation")
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <div class="container-fluid">
                <h2>New Violation</h2>
                <div class="alert alert-success">
                    <p><strong>Create Success</strong></p>
                    <p>New violation created successfully</p>
                </div>
                @Html.ActionLink("Go back", "Create", "Violation")
            </div>

        </div>
    </div>
</div>

DAIS_ASP/Views/Violation/Detail.cshtml
@{
    DAIS_ORM.Database.Violation violation = ViewBag.Violation;
    
}}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                @Html.Partial("SubMenuViolation")
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <h1 class="page-header">Violation detail</h1>
            <div class="container-fluid">
                <ul class="list-group col-xs-4">
                    <li class="list-group-item">Type: @violation.Type</li>
                    <li class="list-group-item">Date: @violation.Date.ToShortDateString()</li>
                </ul>
                <ul class="list-group col-xs-4">
                    <li class="list-group-item">Officer: @Html.ActionLink(violation.Officer.Number.ToString(), "Detail/" + violation.Officer.Number.ToString(), "Officer")</li>
                </ul>
            </div>
            <div class="container-fluid">
                <ul class="list-group col-xs-4">
                    <li class="list-group-item">Birth number: @violation.Violator_Vehicle.Violator.BirthNumber</li>
                    <li class="list-group-item">First name: @violation.Violator_Vehicle.Violator.FirstName</li>
                    <li class="list-group-item">Last name: @violation.Violator_Vehicle.Violator.LastName</li>
                    <li class="list-group-item">Phone: @violation.Violator_Vehicle.Violator.Phone</li>
                </ul>
                <ul class="list-group col-xs-4">
                    <li class="list-group-item">Licence number: @violation.Violator_Vehicle.Vehicle.LicenceNumber</li>
                    <li class="list-group-item">Manufacturer: @violation.Violator_Vehicle.Vehicle.Manufacturer</li>
                    <li class="list-group-item">Model: @violation.Violator_Vehicle.Vehicle.Model</li>
                    <li class="list-group-item">Year of manufacture: @violation.Violator_Vehicle.Vehicle.YearOfManufacture</li>
                </ul>
            </div>

            <h2 class="sub-header">Tickets</h2>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Date</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (DAIS_ORM.Database.Ticket ticket in ViewBag.Tickets)
                        {
                            <tr>
                                <td>@ticket.Id</td>
                                <td>@ticket.Date.ToShortDateString()</td>
                                <td>@ticket.Amount</td>
                                @if(Int32.Parse(ticket.Status) == 1)
                                {
                                    
                                    @: <td>Paid</td>
                                    @: <td></td>
                                }
                                else
                                {
                                    @: <td>Open</td>
                                    <td>@Html.ActionLink("Pay", "Pay", new { Id = ticket.Id})</td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

DAIS_ASP/Views/Violation/Index.cshtml
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                @Html.Partial("SubMenuViolation")
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <h1 class="page-header">Violations</h1>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Type</th>
                            <th>Date</th>
                            <th>Violator</th>
                            <th>Licence Number</th>
                            <th>Officer</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach( DAIS_ORM.Database.Violation violation in ViewBag.Violations)
                        {
                        <tr>
                            <td>@violation.Id</td>
                            <td>@Html.ActionLink(violation.Type, "Detail/" + violation.Id.ToString(), "Violation")</td>
                            <td>@violation.Date.ToShortDateString()</td>
                            <td>@violation.Violator_Vehicle.Violator.FirstName @violation.Violator_Vehicle.Violator.LastName</td>
                            <td>@violation.Violator_Vehicle.Vehicle.LicenceNumber</td>
                            <td>@Html.ActionLink(violation.Officer.Number.ToString(), "Detail/" + violation.Officer.Number.ToString(), "Officer")</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

DAIS_ASP/Views/Violation/SubMenuViolation.cshtml
<li>@Html.ActionLink("All violations", "Index", "Violation")</li>
<li>@Html.ActionLink("New Violation", "Create", "Violation")</li>
<li>@Html.ActionLink("Violator", "Violator", "Violation")</li>
<li>@Html.ActionLink("Home", "Index", "Home")</li>

DAIS_ASP/Views/Violation/Violator.cshtml
@{
    ViewBag.Title = "Violator";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                @Html.Partial("SubMenuViolation")
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <h1 class="page-header">Violator</h1>

            @if (Request.HttpMethod == "GET")
            {
                using (Html.BeginForm("Violator", "Violation", null, FormMethod.Post, new { @class = "form-inline" }))
                {
                <div class="form-group">
                    @Html.Label("Birth Number", new { @class = "" })
                    @Html.TextBox("violator_birth_number", "", new { @class = "form-control" })
                </div>
                <input type="submit" value="Search" class="btn btn-primary" />
                }
            }
            else if (Request.HttpMethod == "POST")
            {
                <div class="container-fluid">
                    <ul class="list-group col-xs-4">
                        <li class="list-group-item">Birth number: @ViewBag.Violator.BirthNumber</li>
                        <li class="list-group-item">First name: @ViewBag.Violator.FirstName</li>
                        <li class="list-group-item">Last name: @ViewBag.Violator.LastName</li>
                        <li class="list-group-item">Phone: @ViewBag.Violator.Phone</li>
                    </ul>
                    <ul class="list-group col-xs-4">
                        <li class="list-group-item">Birth number: @ViewBag.Violator.Address.State</li>
                        <li class="list-group-item">First name: @ViewBag.Violator.Address.Street</li>
                        <li class="list-group-item">Last name: @ViewBag.Violator.Address.City</li>
                        <li class="list-group-item">Phone: @ViewBag.Violator.Address.Zip</li>
                    </ul>
                </div>

                <h2 class="sub-header">Violations</h2>

                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Type</th>
                                <th>Date</th>
                                <th>Violator</th>
                                <th>Licence Number</th>
                                <th>Officer</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach( DAIS_ORM.Database.Violation violation in ViewBag.Violations)
                            {
                            <tr>
                                <td>@violation.Id</td>
                                <td>@Html.ActionLink(violation.Type, "Detail/" + violation.Id.ToString(), "Violation")</td>
                                <td>@violation.Date.ToShortDateString()</td>
                                <td>@violation.Violator_Vehicle.Violator.FirstName @violation.Violator_Vehicle.Violator.LastName</td>
                                <td>@violation.Violator_Vehicle.Vehicle.LicenceNumber</td>
                                <td>@Html.ActionLink(violation.Officer.Number.ToString(), "Detail/" + violation.Officer.Number.ToString(), "Officer")</td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }

        </div>
    </div>
</div>